name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # This is where you place your autograding tests
      # For more information on this runner, see the documentation at: https://github.com/classroom-resources/autograding-io-grader
      #
      # For example, you could run a test suite like this:

    - name: Test 1 Hanoi
      uses: classroom-resources/autograding-io-grader@v1
      id: test1
      with:
        test-name: test_1
        setup-command: gcc -o hanoi hanoi.c
        command: ./hanoi
        input: ""
        expected-output: "--- Start Configuration ---\ns1: [A, B, C, D] (Top index: 3)\ns2: [] (Top index: -1)\ns3: [] (Top index: -1)\n\n--- Final Configuration ---\ns1: [] (Top index: -1)\ns2: [] (Top index: -1)\ns3: [C, B, A, D] (Top index: 3)\n"
        comparison-method: exact
        timeout: 1
        max-score: 100


    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env: 
        TEST1_RESULTS: ${{ steps.test1.outputs.result }}
      with:
        runners: test1